on:
  schedule:
    - cron: _CRON_
  workflow_dispatch:

name: _SOURCE_

jobs:
  _SOURCE_:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools

      - name: Install package
        run: R CMD INSTALL .

      - name: Test dataset
        run: |
          options("testDownload" = TRUE)
          options("testSource" = "_SOURCE_")
          devtools::load_all()
          testthat::test_file("tests/testthat/test-regional-datasets.R", reporter = c("summary", "fail"))
        shell: Rscript {0}
