on:
  schedule:
    - cron: '36 12 * * *'
  workflow_dispatch:

name: Belgium

jobs:
  test-regional-dataset:
    uses: ./.github/actions/test-regional-datasets.yml
    with: 
      test-source: ${{ github.workflow }}
