on:
  schedule:
    - cron: '36 12 * * *'
  workflow_dispatch:

name: Belgium

jobs:
  test-regional-dataset:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: ./.github/actions/test-regional-datasets.yml
        with: 
          test-source: ${{ github.workflow }}
