on:
  schedule:
    - cron: '36 12 * * *'
  workflow_dispatch:
  push:
    paths:
      - R/Canada.R
      - R/processing.R
      - R/shared-methods
      - R/utils.R
  pull_request:
    paths:
      - R/Canada.R
      - R/processing.R
      - R/shared-methods
      - R/utils.R

name: Canada

jobs:
  Canada:
    uses: ./.github/workflows/test-regional-datasets.yml
    with: 
      test-source: ${{ github.workflow }}
