on:
  schedule:
    - cron: '36 12 * * *'
  workflow_dispatch:

name: Covid19DataHub

jobs:
  Covid19DataHub:
    uses: ./.github/workflows/test-regional-datasets.yml
    with: 
      test-source: ${{ github.workflow }}
