on:
  schedule:
    - cron: '36 12 * * *'
  workflow_dispatch:

name: Cuba

jobs:
  Cuba:
    uses: ./.github/workflows/test-regional-datasets.yml
    with: 
      test-source: ${{ github.workflow }}
