on:
  schedule:
    - cron: '36 12 * * *'
  workflow_dispatch:

name: Netherlands

jobs:
  Netherlands:
    uses: ./.github/workflows/test-regional-datasets.yml
    with: 
      test-source: ${{ github.workflow }}
