name: "Workflow_source_exists"

on: [push, pull_request]

jobs:
  Workflow_source_exists:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install package
        run: R CMD INSTALL .

      - name: Check workflow found
        run: |
          library("covidregionaldata")
          source("inst/test-github_workflow_present.R")
        shell: Rscript {0}
